name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
    ### Manuelle Versonierung 
      frontend_version:
        description: 'Frontend-Image-Version (z. B. 1.2.3 oder latest)'
        required: false
        default: 'latest'
      backend_version:
        description: 'Backend-Image-Version (z. B. 1.2.3 oder latest)'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected versions
        run: |
          echo "Frontend-Version: ${{ github.event.inputs.frontend_version }}"
          echo "Backend-Version: ${{ github.event.inputs.backend_version }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ### Init
      - name: Pull backend image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.event.inputs.backend_version }}

      - name: Pull frontend image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.event.inputs.frontend_version }}

      - name: Run backend container
        run: docker run -d --name backend -p 3001:3001 ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.event.inputs.backend_version }}

      - name: Run frontend container
        run: docker run -d --rm --name frontend -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.event.inputs.frontend_version }}

      ### Test
      - name: Wait for frontend to start
        run: sleep 5

      - name: Test frontend container
        run: curl -f http://localhost:3000 || exit 1

      - name: Wait for backend to start
        run: sleep 5

      - name: Test backend container
        run: |
          for i in {1..3}; do
            if curl -f http://localhost:3001/api/ping; then
              echo "Backend is up!"
              exit 0
            else
              echo "Waiting for backend to start..."
              sleep 3
            fi
          done
          echo "Backend did not respond in time."
          exit 1

